### ISSUE TITLE
How do I change font size?

### ISSUE THREAD

**Issue by vedmant** [hoiheart/vue-diff#49]
How do I change font size, changing font size of parent tag doesn't have an effect, I don't see any option to change font size. Changing font size of `.vue-diff-viewer` also doesn't work properly as line heights stay the same.

**Comment by ahmet-v** [comment]
You can try:

```scss
.vue-diff-viewer {
    pre {
        code {
            span {
                font-size: 13px;
            }
        }
    }
}
```
